### ISSUE TITLE
MPV Easy Player 0.330.12 - Multilanguage GUI issues

### ISSUE THREAD

**Issue by bovirus** [422658476/MPV-EASY-Player#23] opened 2021-08-09 10:12 UTC
@422658476 

There are some issue regarding multilanguage GUI
Pelase check screenshots.

![MPV Easy Player 033 0 12 - GUI 01](https://user-images.githubusercontent.com/1262554/128691095-ee5528a1-ebdc-4cc2-bcc6-8e87d0b7d301.jpg)

![MPV Easy Player 033 0 12 - GUI 02](https://user-images.githubusercontent.com/1262554/128691100-f0b721d5-7f60-41e1-808b-3ffebd74d46a.jpg)

![MPV Easy Player 033 0 12 - GUI 03](https://user-images.githubusercontent.com/1262554/128691102-48694210-4968-4aa2-875f-df3ada250cbb.jpg)

![MPV Easy Player 033 0 12 - GUI 04](https://user-images.githubusercontent.com/1262554/128691104-ef59a426-2dde-4788-a6a8-279dffbe17c0.jpg)

![MPV Easy Player 033 0 12 - GUI 05](https://user-images.githubusercontent.com/1262554/128691105-8a7a08db-303c-4133-a344-0cf5361d1ba0.jpg)

![MPV Easy Player 033 0 12 - GUI 06](https://user-images.githubusercontent.com/1262554/128691106-1cdea062-6fd3-4b18-8e16-baf9ef5fdc06.jpg)

![MPV Easy Player 033 0 12 - GUI 07](https://user-images.githubusercontent.com/1262554/128691107-d7737f9d-d027-4102-a186-878a10096d56.jpg)

![MPV Easy Player 033 0 12 - GUI 08](https://user-images.githubusercontent.com/1262554/128691204-ab8fa814-db9a-49cb-b189-027fd049d430.jpg)

![MPV Easy Player 033 0 12 - GUI 09](https://user-images.githubusercontent.com/1262554/128691163-41ea42d6-490a-48ff-9c65-b86324f61e38.jpg)

![MPV Easy Player 033 0 12 - GUI 10](https://user-images.githubusercontent.com/1262554/128691164-e07f0c47-d5d1-4056-97d2-d04d0f7277e2.jpg)

![MPV Easy Player 033 0 12 - GUI 11](https://user-images.githubusercontent.com/1262554/128691165-e5a2bbee-ed27-4c19-84b8-d3871344db65.jpg)

![MPV Easy Player 033 0 12 - GUI 12](https://user-images.githubusercontent.com/1262554/128691167-0bd18467-64e6-40f5-aba5-bf27449bae04.jpg)

**Comment by 422658476** [comment] 2021-08-09 10:35
The options in the setting drop-down menu are in English no matter what language, because the content of the options is exactly the same as the value set by mpv, and it is not translatable by default.
Video(1) and audio(1) are correct in themselves, because if there is a second tab page that is video(2), audio(2), this should also be found and translated in the translation file.
osc(A), osc(1), osc(2) are English abbreviations, the meaning of this abbreviation has been described in detail in osc(A), osc(1), if translated into other languages, then other settings will use this The abbreviations must be revised, so it is recommended to maintain the status quo without translation.
The names osc(A), osc(1), and osc(2) are also correct, because osc(A) is for mpv-easy borderless gui, and osc(1) and osc(2) are for mpv native gui. It needs to be distinguished in this way.
For the remaining untranslated parts that are circled, do you update the language file to me or need me to do other operations, because these untranslated parts should be in the translation file you provided to me.
Thank you so much for the feedback

**Comment by bovirus** [comment] 2021-08-09 11:56
@422658476

I checked italian language files and is 100% translated.
In previous MPV Easy Player version (0.33.0.11) most of the strings were translated.

Then probably some strings are changed in source files.
Please check and update language files.

Thanks.

**Comment by 422658476** [comment] 2021-08-09 11:59
Okay, I will download the language file you provided to me last time and process it again to see if there will be any changes.
Many thanks

**Comment by 422658476** [comment] 2021-08-09 12:12
I downloaded language.zip again
I first found the first place that was not translated, but please see the screenshot, this seems to have not been translated into Italian. I am looking for other parts that have not been translated. Please help me to reconfirm whether the language file is translated.
Many thanks 
![Uploading 1.png…]()

**Comment by 422658476** [comment] 2021-08-09 12:16
It should be that these parts were missed in the translation, I found a few others, the Italian translation is also in English

**Comment by 422658476** [comment] 2021-08-09 12:19
It seems from your last message that the translation of the setting interface is not 100% 
==================================
This is the first step of italian language files.
EasyGUI 100% translated.
Easy Settings is not 100% translated but most of them.
Optimized fiels after a long test about GUI in place.
Please rename them (github repository need anotehr langaueg file name then application), load in your system and run lupdate to align this file to yoiur source.

What's the meaning of "[Cycle]" in translation?
======================================

**Comment by bovirus** [comment] 2021-08-09 12:24
@422658476 

The error/misudnerstanding was all strings are marked as green.
Then is not so easy to check if somethings changes becasue are all always green.
Then for each new translation I have to check from first line which line are translated and other not.

On QT standard the lines with changes are marked with yellow tick (no green tick).

**Comment by 422658476** [comment] 2021-08-09 12:31
The problems you encounter are easy to encounter when translating.
Then I wait for you to update the language file to me, thank you very much.
You can get the latest language files (*.ts) in the language file, they have been synchronized by me, just modify them.
Many thanks.

**Comment by bovirus** [comment] 2021-08-09 13:35
@422658476 

Could be interesting when you update the .ts files if they can marked new/changed strings with yellow tip (instead green tick).

**Comment by 422658476** [comment] 2021-08-09 13:43
Usually qt linguist detects the difference is red, only when the qt linguist feels that the translation is biased will it be a yellow mark. 

I have been using lupdate and lrelease in qt linguist and qt creator

**Comment by 422658476** [comment] 2021-08-09 13:49
The problem now is that the part of the Italian file that should be translated into Italian is not a vacancy, but is filled with English, so this is not detectable and marked as red. It can only be manually confirmed. It may be because you have previously It was caused by first filling in English and then modifying it to Italian. Otherwise these untranslated parts should be blank.

**Comment by bovirus** [comment] 2021-08-09 13:53
@422658476 

I found a solution.
With lconvert I converted .ts file in .po file.
With POEditor I marked the 47 strings currently in English as fuzzy strings (not checked) using "CTRL+U" and I saved the .po file.
Then with lconvert I converted .po file (with fuzzy strings) in .ts file.
Now the .ts file show me with yellow ? the strings to check (fuzzy).

Thanks.

**Comment by 422658476** [comment] 2021-08-09 14:01
Google Translate does not translate the meaning very well, so I can't understand what you mean, but I don't recommend it.
Using the qt tool, I will only save files in two formats, ts and qm.
If you want to find all the parts in Italian that are not translated and are now in English, you only need to use a text comparison software (such as beyone compare) to compare English .ts and Italian .ts. The same part of the two files is untranslated. The Italian part, because the text of these parts in the two files are the same.
If you don't have such software, I can give you a screenshot of the comparison result.

**Comment by 422658476** [comment] 2021-08-09 14:05
Text comparison software doesn't work at all, omg.

**Comment by 422658476** [comment] 2021-08-09 14:22
I modified the ts file and added extra [xxxxxxx] characters to the English translation part of the Italian file. You only need to use qt linguist to open the ts file, use the search function to search for xxxxxx, then the searched content is not The translated part.
You just need to keep searching for the next one until the end.
Hope this can help you. 
[it.zip](https://github.com/422658476/MPV-EASY-Player/files/6955118/it.zip)

**Comment by bovirus** [comment] 2021-08-09 15:50
Hello.

Thanks.

Sorry but I didn't understand because you cannot translate simple words like

GUI mode -> Execution mode -> idele/belownormal/normal/abovenormale/high/realtime
Video -> Discard frames -> vo ???? what's this
Video -> Decoding mode? auto-safe/ auto-copy?
Video -> Disable video adapting -> no/yes/downscale-big
Audio -> Audio channel -> auto-safe
OSC - Box style -> box/box-original/slimbar/webplayer/one-to-one/1-2-1 (why one-to-one and 1-2-1 in different mode?)
OSC -> Sekking bar style -> bar/bar-alpha/line/line-alpha
OSD -> OSD axis position -> left/center/right - top/center/bottom

Thanks.

**Comment by 422658476** [comment] 2021-08-09 16:24
The options in the drop-down menu are very easy to translate from the translator's point of view, just convert the word into another word. But from a programming point of view, this is very difficult, because these options must be consistent with what mpv can read, and mpv can only recognize the corresponding options in English. If you translate it into other languages, read and write These values ​​will be very complicated and error-prone.
For example: there is a setting in the setting file
size=aaa #Optional values ​​include: aaa, bbb, ccc.
When you translate aaa, bbb, ccc into jjj, kkk, LLL, the problem arises.
When the code reads the value of size from xxx.conf, it must first determine whether it is one of aaa, bbb, or ccc. If it is aaa, set the value in the drop-down menu to aaa.
But after translation, the value in the drop-down menu has changed to jjj, kkk, LLL (translation is read before setting).
If the read value is aaa, then the corresponding value in the drop-down menu is jjj at this time, and you must write a piece of code. When the value is aaa, set the value of the drop-down menu to jjj.
The same is true when saving. If the current option is detected as jjj when saving, then a piece of code needs to be handwritten. When the value is jjj, the size value in xxx.conf is set to aaa.
This is just a switch between two languages, which is quite scary. In fact, there are more problems, so keeping only the English option is the best choice.
I don't know if Google Translate can translate these translations for you to understand.

**Comment by bovirus** [comment] 2021-08-09 17:14
@422658476 

Ok. Thanks for the explanation.

**Comment by 422658476** [comment] 2021-08-10 18:47
I may have some problems with the operation of pull requests. If it does not meet expectations, please submit an issue again, because I am completely unfamiliar with this.
However, after I synchronized the Italian language and converted it to qm files, the parts that were not translated before became Italian. I believe there should be no problem with pull requests.
I will close this issue, and the latest Italian translation will be used in the next version (maybe 1 month).

**Closed by 422658476** 2021-08-10 18:47 UTC
