### ISSUE TITLE
Keyboard Shortcut for Full Screen Bug 

### ISSUE THREAD

**Issue by codeduph** [422658476/MPV-EASY-Player#98] opened 2024-11-10 01:13 UTC
the keyboard shortcut for full screen does not work "**enter**"... using windows 10.... 

https://github.com/user-attachments/assets/94612e15-b026-4e7b-8c9f-3b1cc1e97d3a

BTW, all keyboard shortcut keys are working except for "enter"....

**Comment by 422658476** [comment] 2024-11-10 04:38
This is not a bug. To achieve the function, mpv-easy player directly sends the shortcut key to mpv for processing. So when you press a shortcut key, the gui and mpv programs actually receive the key command at the same time. No one wants to press a key to trigger two different behaviors. So the enter and esc keys are specially processed. One of them is that enter will not have the behavior of entering full screen under the mpv-easy borderless gui. For example: when you open the command line console in the player and enter a command to mpv and press enter, you don’t want to enter full screen at the same time. Esc is similar but the behavior is different. When you use esc to exit the command line, you think it is natural, but performing this operation in full screen will also trigger the exit full screen behavior.
Additional tips: There are 2 bugs in the current shortcut keys. Double quotes and backslashes cannot be entered. This problem will be fixed in the next version.

**Closed by 422658476** 2024-11-10 04:38 UTC
