### ISSUE TITLE
migaku addon shut down

### ISSUE THREAD

**Issue by HoanPiTa** [422658476/MPV-EASY-Player#55] opened 2022-11-12 02:52 UTC
hi u can't use migaku addon on this. On MPV everything workwell

log text
ARGS: ['C:\\Users\\HP\\Downloads\\Programs\\MPV-EASY Player V0.34.0.7\\data\\portable-data/scripts/migaku_mpv/migaku_mpv', '\\\\.\\pipe\\mpvsocket']
CFG: {'browser': 'default', 'reuse_last_tab': 'yes', 'reuse_last_tab_timeout': '1.5', 'sub_font_name': 'Noto Sans CJK JP Regular', 'sub_font_size': '48', 'sub_bottom_margin': '22', 'sub_outline_size': '3', 'sub_shadow_offset': '0', 'host': '127.0.0.1', 'port': '2222', 'port_max': '2233', 'skip_empty_subs': 'yes', 'subtitle_export_timeout': '7.5', 'anki_image_width': 'auto', 'anki_image_height': 'auto', 'anki_image_format': 'jpg', 'anki_audio_format': 'wav'}
BRS: None
ANKI: {'mpv_executable': 'mpv', 'mpv_cwd': 'C:\\Users\\HP', 'tmp_dir': 'C:\\Users\\HP\\Downloads\\Programs\\MPV-EASY Player V0.34.0.7\\data\\portable-data\\scripts\\migaku_mpv\\tmp', 'migaku_dict_host': '127.0.0.1', 'migaku_dict_port': 12345, 'image_format': 'jpg', 'audio_format': 'wav', 'image_width': None, 'image_height': None}
EXES: {'ffmpeg': 'C:\\Users\\HP\\Downloads\\Programs\\MPV-EASY Player V0.34.0.7\\data\\portable-data\\scripts\\migaku_mpv/ffmpeg.exe', 'ffsubsync': 'C:\\Users\\HP\\Downloads\\Programs\\MPV-EASY Player V0.34.0.7\\data\\portable-data\\scripts\\migaku_mpv/ffsubsync/ffsubsync.exe', 'rubysubs': None}
--------------
UNHANDLED EXCEPTION OCCURED:

Platform: Windows-10-10.0.19041-SP0
Python: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Traceback (most recent call last):
  File "\\VBoxSvr\JP\Windows\migaku_mpv\migaku_mpv.py", line 767, in <module>
  File "\\VBoxSvr\JP\Windows\migaku_mpv\migaku_mpv.py", line 725, in main
  File "utils\mpv_ipc.py", line 11, in __init__
  File "utils\mpv_ipc.py", line 105, in port_open
OSError: Opening pipe failed

EXITING

**Comment by 422658476** [comment] 2022-11-12 10:31
According to the log [OSError: Opening pipe failed], this problem is caused by the script not opening the pipe correctly.

This script may create and use pipes and mpv for interprocess communication.

But unfortunately, mpv-easy player also uses this method to communicate with mpv between processes.

It is very likely that since mpv-easy player is already using this pipe to communicate with mpv, it cannot be used, so the opening fails.

The mpv documentation describes three ways to communicate with mpv:
1. The communication method between gui front end and mpv: pipe pipeline. That is the way mpv-easy player uses.
2. Use libmpv.
3. Script. That is, directly obtain the data in mpv directly through the commands in the script.

Unfortunately, migaku-mpv as a script may use the gui front-end to capture data and then process it, usually as a script does not need to use this more complicated way. However, this script folder also contains exe files. Maybe the author thinks that it is better to use a pipe to capture data. In this way, this script actually acts as a part of the gui front-end, which also causes conflicts.

If the script author cannot directly capture the required data for processing by rewriting the normal script, then:
This script is recommended for use in mpv only.

You may need to consult the author of the script and let him handle this.

**Comment by 422658476** [comment] 2022-11-14 10:03
@HoanPiTa 

If there is no problem please close this issue

**Closed** 2022-11-14 13:52 UTC
