### ISSUE TITLE
External language files (like .ts/.qm QT language files)

### ISSUE THREAD

**Issue by bovirus** [422658476/MPV-EASY-Player#20] opened 2021-07-20 07:44 UTC
@422658476 

Hello.
Many thanks for your projects.
Could be possible to have language files external instead integrate in the program?
In this way could be easy add/test new languages (like Italian).

Thanks.

**Comment by 422658476** [comment] 2021-07-20 09:35
Sorry, this is something I did not consider. I should add a language folder so that others can add additional language files for testing or use. I will complete this function as soon as possible, thank you very much.
I am not familiar with the functions of github, so I may need to know how to use the pull requests function to meet your needs.

**Comment by 422658476** [comment] 2021-07-20 09:55
<message>
        <location filename="../qmpv_mainwindow.ui" line="2614"/>
        <source>2倍</source>
        <translation>2 speed</translation>
        <translation>speed 3x</translation>
    </message>
    <message>
        <location filename="../qmpv_mainwindow.ui" line="2619"/>
        <source>2.5倍</source>
        <translation>2.5 speed</translation>
        <translation>speed 3.5x</translation>

==================================
There may be a problem with the new translation,
speed 3x => speed 2x
speed 3.5x => speed 2.5x 

======
Sorry, the pull requirement function may have to be processed after the external language file switching function is completed. I don’t understand this function at all.

**Comment by bovirus** [comment] 2021-07-20 10:14
@422658476

Correct.

Now the english language should be OK.

Pelase add in your repository the language fiels to avoid me to the same job a new time.

Then you can majke the changes in source code.

**Comment by 422658476** [comment] 2021-07-20 15:56
Now you can start testing Italian.
Please download the attachment mpv-easy 20210720-2344.zip
It contains the improved exe and language, you only need to overwrite these files.
The 2 it.ts you made can be converted into 2 it.qm using qt linguist (using the [Release] function under [Save] in the [File] menu, the one with (R))
One renamed to it-mpveasysettings.qm
Rename the other to it-mpveasygui.qm
Note that the letters are all lowercase.
Put these two files in the language folder to overwrite the existing sample files.
Run MpvEasySettings.exe, switch to Italian, and re-run the program to see the interface language change.
  For the pull you submitted, I need to check the difference tomorrow or more before it can be synchronized to the program. Thank you very much. If you have any questions, please submit an issue again. 
[mpv-easy 20210720-2344.zip](https://github.com/422658476/MPV-EASY-Player/files/6849715/mpv-easy.20210720-2344.zip)

**Comment by bovirus** [comment] 2021-07-20 16:00
@422658476 

First of all I see thank you for this opprtruninty.
I have a good knledge about QT development, use of QTLinguist, and lrelease/lconvert exe tool.
I will do all necessaryu steps.

If you need more help I can do any job about merge/splitting language files.

Thanks again.

**Comment by 422658476** [comment] 2021-07-20 16:09
It’s great. It’s great to meet someone who is familiar with qt. Although I have used qt to make a large part of this program, I am still not familiar with many functions of qt.
Tomorrow, there is a high probability that I will first clean up the outdated translation code in ts, just like you did, and then compare and synchronize the code you gave.

**Comment by bovirus** [comment] 2021-07-20 16:13
For final version I propose to use language file scheme like

mpveasygui_xx.ts (mpveasygui_cn.ts/mpveasygui_en.ts/mpveasygui_it.ts)
mpveasysettings_xx.ts (mpveasysettings_cn.ts/mpveasysettings_en.ts/mpveasysettings_it.ts)

**Comment by bovirus** [comment] 2021-07-20 16:16
I copied from qt 5.12.11 (MS Visual C++ 64bit) the library files

Qt5Gui.dll
Qt5Network.dll
Qt5Widgets.dll

That progam report me as me as mssing. but after that it didn't work.
Error 0x0000007b

**Comment by 422658476** [comment] 2021-07-20 16:26
My consideration is: when there are many language files, use file name sorting:
it-mpveasysettings.qm
it-mpveasygui.qm
2 files are always displayed together, if used
mpveasygui_it.qm
mpveasysettings_it.qm
Then the two files will be far apart, and it will be difficult to find if one of them is missing.

You only need to use the installation package provided under release. This is a complete program that contains all the required dlls.
I am using qt mingw 32bit 5.6.3
So it must be an error.
MPV-EASY Player uses 32-bit qt regardless of whether it is 32bit or 64bit, but one of mpv is 32bit and the other is 64bit.
Because qt does not officially provide mingw64

**Comment by bovirus** [comment] 2021-07-20 16:28
Using only exe in your package get an error message about missing dll.

**Comment by 422658476** [comment] 2021-07-20 17:56
I'm very sorry, I found a serious bug, please use the mpv-easy player 20210721-0152.zip provided below to overwrite the same file and debug it.
Fixed bug: After selecting Italian in the setting interface, after re-running MpvEasySettings.exe, the interface will not be displayed in Italian 
[mpv-easy player 20210721-0152.zip](https://github.com/422658476/MPV-EASY-Player/files/6850339/mpv-easy.player.20210721-0152.zip)

**Comment by bovirus** [comment] 2021-07-20 17:57
@422658476 

I tested 32bit and it seems to work.
I installed stable 32bit version and overwrite the exe with 2 new ones.
And copy in MPV Easy Player the language fodler.
Now Italian language is available in "Language" selection.
Great!!! Thanks.

It seems that 64bit stable version didn't work fine in ame configuration.
Create an error during running.
I will check later.

**Comment by 422658476** [comment] 2021-07-20 17:57
I'm very sorry, I found a serious bug, please use the mpv-easy player 20210721-0152.zip provided below to overwrite the same file and debug it.
Fixed bug: After selecting Italian in the setting interface, after re-running MpvEasySettings.exe, the interface will not be displayed in Italian
[mpv-easy player 20210721-0152.zip](https://github.com/422658476/MPV-EASY-Player/files/6850344/mpv-easy.player.20210721-0152.zip)

**Comment by bovirus** [comment] 2021-07-20 17:58
@422658476 

If you want to encourage other tramslators to make a new tramslation probably could be better to have as source language English (now is Chinese).

**Comment by 422658476** [comment] 2021-07-20 18:02
I know, but it’s too late. Everything was designed in Chinese at the beginning. I broke this principle and found out that it was too late. I am not going to change it to English again because my English is not very good. Well, if I use English as the most basic interface language, then many times I will not understand what the above is.

**Comment by 422658476** [comment] 2021-07-20 18:06
If the information on the github page you said is based in Chinese and should be written in English, the same problem is that English is not my native language. It is a nightmare to translate these into English to write. I have experienced this nightmare once, that is Translate mpv-easy player into English, hahahaha

**Comment by 422658476** [comment] 2021-07-21 07:45
Hello, I have compared the changes of pull, and it is completely possible, except that speed 0.2 (1/5) is not translated into speed 0.2x, which I have manually changed, and I have updated it to the program.
The language file of MpvEasySettings removes two parts that do not need to be translated.
Now I have updated all the language files on github, I don’t know if this will cause you trouble.

**Comment by bovirus** [comment] 2021-07-21 09:49
[language.zip](https://github.com/422658476/MPV-EASY-Player/files/6854589/language.zip)

This is the first step of italian language files (EasyGUI 100% translated / Easy Settings is not 100% translated).
Optimized after a long test about GUI in place.
Please rename them (github repository need anotehr langaueg file name then application), load in your system and run lupdate to align this file to yoiur source.

Thanks.

**Comment by 422658476** [comment] 2021-07-21 09:56
Does the language file let me see the current state, and then I don’t need to do anything or do ? ? ?
[Cycle] means to continuously switch between two states, such as cycle pause, then playback pause, cycle pause again, playback continues, cycle pause again, playback pause,

**Comment by 422658476** [comment] 2021-07-21 12:26
in the MpvEasyGui English language file ：Loop playlist and shuffle: forever ===> oop playlist and shuffle: enable
The English translation changes of the MpvEasySettings menu part have been synchronized with the MpvEasyGui menu

**Comment by 422658476** [comment] 2021-08-02 13:18
Now I have updated the language files on github. Whether this meets your requirements, I updated github according to my understanding.
If you want to help add more other languages, this is no problem, very welcome, I can give you the improved exe file as before.
You only need to provide me with 2 things through text
Italian ==》 it.ts

language ==> ??.ts

I need to know the type of language [language] and the file name of the language [??.ts], so that I can add and make into the program, the program also knows which language files to load, and then I will still provide 2 improvements The exe file for you, you can load the corresponding language file for translation and debugging.

**Comment by bovirus** [comment] 2021-08-02 13:31
@422658476 

For this moment no need to add other languages.
Language file format is .TS.

I asked to released a new official build and put it here

https://github.com/422658476/MPV-EASY-Player/releases

that add for all users the italian languages.

Then anyone that download it can use Italian language.

Please also update mpv core program (01.08.2021).

Please also think is is not better to distribute two separate zip (not exe) with 

32bit mpv easy player + 32bit mpv core
64bit mpv easy player + 64bit mpv core

Thanks.

**Comment by 422658476** [comment] 2021-08-02 13:41
Okay, there may be some errors in my understanding or the online translator I use.
The next version will be released this week or next week. I thought you might also update the language file, so I didn't release it immediately.
Except for the last one: use zip
At present, the installation package with the exe suffix is actually a compressed file, because it only has compression and decompression functions. By using the lzma compression method, it can provide users with a smaller program package, which is actually the same as zip.

**Comment by bovirus** [comment] 2021-08-02 13:51
@422658476 

For me the same exe that has two option: 32bit (default) or 64bit coiuld be quite complex for most users (and most of them don't install 64bit).
Could be probably better to have two exe files: one for 32bit and one for 64bit.

Please when you will update language files, advise me in advance, before to release a new version program version, to enable me to update italian langauge files, and reelase trhe new program with italian language updated.

**Comment by 422658476** [comment] 2021-08-02 14:04
Okay, next time there is a change in the language, I will notify you as much as possible so that the Italian language files can be synchronized before the new version of the program is released.
The program with both 32-bit and 64-bit versions will remain the same in this respect. It cannot be as you wish. I'm sorry for that. Since this is a portable software, a program contains 2 versions. After you download it, you can easily switch between the 32-bit and 64-bit versions, because you only need to delete the folder where the program is located.
I will close this issue now. If there are any problems, please open the issue.
Thank you very much for all your hard work in the previous 2 weeks, thank you very much.

**Closed by 422658476** 2021-08-02 14:04 UTC

**Comment by bovirus** [comment] 2021-08-02 14:06
@422658476 

I agree with you.
Please close this issue.
